Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,15 +24,15 @@ jobs:
           sudo apt install -y software-properties-common
           sudo add-apt-repository universe
           sudo apt update
-          sudo apt install -y libunwind-dev
+          sudo apt install -y libunwind-dev autoconf automake libtool
           sudo apt install -y build-essential ccache \
-            libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev \
-            libpng-dev python3-pip python3-setuptools zip unzip openjdk-8-jdk \
-            git python3 python3-dev \
-            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
-            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
-            libfreetype6-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
-            libmtdev-dev libncurses-dev pkg-config
+           libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev \
+           libpng-dev python3-pip python3-setuptools zip unzip openjdk-8-jdk \
+           git python3 python3-dev \
+           libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
+           libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
+           libfreetype6-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
+           libmtdev-dev libncurses-dev pkg-config
 
       - name: Install Buildozer and Cython
         run: |
@@ -46,10 +46,20 @@ jobs:
             buildozer init
           fi
 
+      - name: Run autoupdate
+        run: |
+          if [ -f configure.ac ]; then
+          autoupdate
+          fi
+
       - name: Install Android SDK and NDK
         run: |
           yes | buildozer android update
 
       - name: Build APK
         run: |
-          buildozer android debug --verbose
+         buildozer android debug --verbose
+         if [ $? -ne 0 ]; then
+         echo "Build failed. Check logs for details."
+         exit 1
+         fi
